### ISSUE TITLE
Copyright problem

### ISSUE THREAD

**Issue by jacobq** [adrienbailly/STM32-CMake-CodeSourcery#1]
Not that I personally care, but I think technically the copyright holder for the start-up code and linker script (Atollic AB) does not permit that to be published/redistributed.

e.g. see https://github.com/adrienbailly/STM32-CMake-CodeSourcery/blob/995109a49c7c22f843e58da10ed648ca190ab444/lkr/stm32f407vg_flash.ld#L21-L27

**Comment by adrienbailly** [comment]
Thanks for noticing
